version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/App.Dockerfile
    container_name: app
    command: bash -c "npm run start:dev"
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app:cached
    restart: always
    ports:
      - 3000:3000
    links:
      - mongodb
      - mysql

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app
